### ISSUE TITLE
Feature Request: Send to microsoft teams

### ISSUE THREAD

**Issue by jessequinn** [Matrix86/driplane#3]
would it be possible to send to teams?

for instance i have the need for RSS feeds to be sent to teams.

**Comment by Matrix86** [comment]
Like for Slack you could create a Webhook and use that to write a message on a channel. 
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors

**Comment by jessequinn** [comment]
you are saying use the slack component but pass it a teams webhook?

**Comment by jessequinn** [comment]
or modify the slack go file for teams?
